# Generated by Django 3.1.4 on 2021-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakeinfo',
            name='latin_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
