# Generated by Django 3.1.4 on 2021-02-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20210117_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.snakeinfo')),
                ('snake_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.snakeimage')),
            ],
        ),
    ]
