# Generated by Django 3.1.4 on 2021-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_auto_20210305_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakeinfo',
            name='short_desc',
            field=models.TextField(default='WIP'),
            preserve_default=False,
        ),
    ]
